### ISSUE TITLE
Can seem to get this to work with Alfresco CE 5.0

### ISSUE THREAD

**Issue by JeroenKool** [skomarica/alfresco-share-create-link#4] opened 2015-08-19 04:31 UTC
Installed as instructed from release AMP(s). Catalina.out shows no errors whatsoever, but function is not showing up in share, what am I missing here?
Running Community - 5.0.0 (d r99759-b2)

**Comment by skomarica** [comment] 2015-08-19 16:00
I was not able to reproduce this issue on clean 5.0.d instance, so I assume you haven't applied AMP's correctly.

Please be sure that both AMP's are correctly applied: <B>create-link-repo.amp</B> to <B>alfresco.war</B> and <B>create-link-share.amp</B> to <B>share.war</B> application. If you use <B>apply_amps</B> script, the output should be something like:

```
This script will apply all the AMPs in C:\Alfresco2\amps to the alfresco.war and share.war files in C:\Alfresco2\tomcat\webapps
Press control-c to stop this script . . .
Press any key to continue . . .
Module 'create-link-repo' installed in 'C:\Alfresco2\tomcat\webapps\alfresco.war
'
   -    Title:        create-link-repo AMP project
   -    Version:      1.0.0.1410011040
   -    Install Date: Wed Aug 19 17:26:49 CEST 2015
   -    Description:   Manages the lifecycle of the create-link-repo AMP (Alfresco Module Package)
Module 'create-link-share' installed in 'C:\Alfresco2\tomcat\webapps\share.war'
   -    Title:        create-link-share AMP project
   -    Version:      1.0.0.1410011042
   -    Install Date: Wed Aug 19 17:26:51 CEST 2015
   -    Description:   Manages the lifecycle of the create-link-share AMP (Alfresco Module Package)
.
About to clean out tomcat/webapps/alfresco directory and temporary files...
Press any key to continue . . .
```

After starting the tomcat, ensure that you have these lines in your alfresco.log (or catalina.out):

```
 2015-08-19 17:28:46,829  INFO  [repo.module.ModuleServiceImpl] [localhost-startStop-1] Found 1 module(s).
 2015-08-19 17:28:46,924  INFO  [repo.module.ModuleServiceImpl] [localhost-startStop-1] Installing module 'create-link-repo' version 1.0.0.1410011040.
```

You can also validate if modules directories exist:

```
tomcat\webapps\alfresco\WEB-INF\classes\alfresco\module\create-link-repo
tomcat\webapps\share\WEB-INF\classes\alfresco\module\create-link-share
```

**Comment by mathieuga** [comment] 2015-08-26 13:48
For information installed with success alfresco-share-create-link with Alfresco 5.0.d Community.
Thniks again for this good amp.

**Comment by skomarica** [comment] 2015-09-07 20:44
Thank you for your validation @mathieuga 

Closing issue as it can't be reproduced. If more information appears later, please reopen the issue.

**Closed by skomarica** 2015-09-07 20:44 UTC
